// <auto-generated />
namespace SharpFlashCard.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class csharp_flashcards : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(csharp_flashcards));
        
        string IMigrationMetadata.Id
        {
            get { return "201503050921579_csharp_flashcards"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
